import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {scryptSync,randomUUID} from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import {createApp} from '../server/app.mjs';
import {passwordHash,passwordMatches,authTransportAllowed} from '../server/security.mjs';
import {verifyWebhook} from '../server/payments.mjs';
const dir=await mkdtemp(path.join(os.tmpdir(),'emberfall-security-')),app=await createApp({port:0,host:'127.0.0.1',dataDir:dir});await app.listen();const base='http://127.0.0.1:'+app.server.address().port;
let checks=0;const pass=name=>{checks++;console.log('PASS',name);};
async function request(session,route,{data,raw,headers={}}={}){const r=await fetch(base+route,{method:data!==undefined||raw!==undefined?'POST':'GET',headers:{...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{}),...(data!==undefined||raw!==undefined?{'Content-Type':'application/json'}:{}),...headers},...(data!==undefined||raw!==undefined?{body:raw??JSON.stringify(data)}:{})});let body;try{body=await r.json();}catch{body={};}return {status:r.status,data:body,headers:r.headers};}
const refresh=(session,r)=>{if(r.headers.get('set-cookie'))session.cookie=r.headers.get('set-cookie').split(';')[0];if(r.data.csrf)session.csrf=r.data.csrf;return r;};
const command=(s,a)=>request(s,'/api/command',{data:{requestId:randomUUID(),...a}});
async function guest(){const r=await request(null,'/api/session',{data:{}});const s={id:r.data.user.id};refresh(s,r);return s;}
try{
 const encoded=await passwordHash('password-for-tests'),second=await passwordHash('password-for-tests');assert.match(encoded,/^scrypt\$32768\$8\$3\$/);assert.notEqual(encoded,second);assert.ok(await passwordMatches('password-for-tests',encoded));assert.equal(await passwordMatches('wrong',encoded),false);const salt='12'.repeat(16),legacy=salt+':'+scryptSync('legacy-password',salt,64).toString('hex');assert.ok(await passwordMatches('legacy-password',legacy));pass('Passwords use salted, bounded asynchronous scrypt and verify legacy hashes');
 const a=await guest(),b=await guest(),old={...a};let r=await request(a,'/api/auth/register',{data:{username:'Security_Chief',password:'correct-password-12'}});assert.equal(r.status,200);refresh(a,r);assert.notEqual(a.cookie,old.cookie);assert.equal((await request(old,'/api/state')).status,401);assert.match(r.headers.get('set-cookie'),/HttpOnly/);pass('Registration rotates the session and revokes the original guest token');
 r=await request(null,'/api/auth/login',{data:{username:'Security_Chief',password:'correct-password-12'}});assert.equal(r.status,200);const device={};refresh(device,r);
 const previous={...a};r=await request(a,'/api/auth/password',{data:{currentPassword:'correct-password-12',newPassword:'new-password-safe-42'}});assert.equal(r.status,200);refresh(a,r);assert.equal((await request(device,'/api/state')).status,401);assert.equal((await request(previous,'/api/state')).status,401);assert.equal((await request(null,'/api/auth/login',{data:{username:'Security_Chief',password:'correct-password-12'}})).status,401);pass('Changing a password revokes other sessions and rejects the previous password');
 assert.equal((await request(a,'/api/command',{data:{type:'collect',requestId:randomUUID()},headers:{'X-CSRF-Token':'forged'}})).status,403);assert.equal((await request(a,'/api/command',{data:{type:'collect',requestId:randomUUID()},headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await request(null,'/api/state')).status,401);pass('Missing sessions, forged CSRF tokens and foreign origins are rejected');
 const before=(await request(a,'/api/state')).data.state;for(const attack of [{type:'set-wallet',gems:9999999},{type:'hero-upgrade',hero:'champion',level:50},{type:'build',building:'__proto__',x:0,z:0},{type:'collect',realm:'__proto__'},{type:'season-claim',tier:20},{type:'capital-donate',amount:-1000}])assert.equal((await command(a,attack)).status,400,JSON.stringify(attack));const after=(await request(a,'/api/state')).data.state;assert.equal(after.gems,before.gems);assert.equal(after.heroes.champion.level,0);assert.equal({}.polluted,undefined);pass('Forged wallets, hero levels, prototype keys, season rewards and negative donations fail');
 for(const raw of ['null','[]','"text"','{bad'])assert.equal((await request(a,'/api/command',{raw})).status,400);assert.equal((await request(a,'/api/command',{raw:'x'.repeat(70000)})).status,413);assert.equal((await request(a,'/api/command',{data:{},headers:{'Content-Type':'text/plain'}})).status,415);pass('Malformed, non-object, oversized and wrong-content-type requests are rejected');
 r=await command(a,{type:'battle-start',mode:'training'});assert.equal(r.status,200);assert.equal((await command(b,{type:'battle-end',battleId:r.data.battleId})).status,404);assert.equal((await command(a,{type:'battle-deploy',battleId:r.data.battleId,troop:'guardian',x:0,z:0})).status,400);await command(a,{type:'battle-end',battleId:r.data.battleId});pass('Players cannot control other players’ battles or deploy at forged coordinates');
 const defenderBefore=(await request(b,'/api/state')).data.state.gold;r=await command(a,{type:'battle-start',defender:b.id});assert.equal(r.status,200);const reserved=r.data.battle.lootEscrow.gold;assert.equal((await request(b,'/api/state')).data.state.gold,defenderBefore-reserved);await command(a,{type:'battle-end',battleId:r.data.battleId});assert.equal((await request(b,'/api/state')).data.state.gold,defenderBefore);pass('Player raid loot is reserved once and unused loot is returned on retreat');
 const page=await fetch(base+'/');assert.match(page.headers.get('content-security-policy'),/script-src 'self'/);assert.match(page.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(page.headers.get('x-frame-options'),'DENY');for(const file of ['/.env','/server/app.mjs','/data/emberfall.sqlite','/.openai/hosting.json','/%2e%2e/server/app.mjs'])assert.equal((await fetch(base+file)).status,404);pass('Security headers restrict scripts and framing; secrets, source and database are not served');
 assert.equal(authTransportAllowed({headers:{host:'game.example.com'},socket:{remoteAddress:'203.0.113.10'}},false),false);assert.equal(authTransportAllowed({headers:{host:'game.example.com'},socket:{remoteAddress:'127.0.0.1'}},false),false);assert.equal(authTransportAllowed({headers:{host:'localhost:8080'},socket:{remoteAddress:'127.0.0.1'}},false),true);assert.equal(authTransportAllowed({headers:{host:'game.example.com'},socket:{remoteAddress:'127.0.0.1'}},true),true);assert.throws(()=>verifyWebhook(Buffer.from('{}'),'t=1,v1='+'0'.repeat(64),'test-secret'));pass('Public account access requires HTTPS and expired or forged payment signatures fail');
 await request(a,'/api/auth/logout',{data:{}});assert.equal((await request(a,'/api/state')).status,401);pass('Sign out revokes the server session immediately');
 console.log(`${checks} security checks passed.`);
}finally{await app.close();await rm(dir,{recursive:true,force:true});}
