import assert from 'node:assert/strict';
import * as M from '../dist/model.js';
import {villageNavigator,advanceRoute} from '../dist/village-paths.js';
import {workItems} from '../dist/village-ui.js';
const s=M.initialState(1000);s.obstacles=[];s.flags=[];s.buildings=[{id:'hall',type:'hall',level:3,x:0,z:0},{id:'barracks',type:'barracks',level:3,x:4,z:4},{id:'camp',type:'camp',level:3,x:-28,z:10}];
const nav=villageNavigator(s),path=nav.route({x:4,z:6},{x:-28,z:12});assert.ok(path?.length);assert.ok(path.some(p=>p.x<-15&&p.x>-23));assert.ok(path.filter(p=>p.x<-14.5&&p.x>-23).every(p=>Math.abs(p.z-12)<=.5));assert.ok(path.every(p=>nav.open(p.x,p.z)));const position={x:4,z:6};advanceRoute(position,path,200);assert.equal(path.length,0);assert.deepEqual(position,{x:-28,z:12});assert.equal(nav.route({x:4,z:6},{x:-28,z:12},true).length,1);
console.log('PASS Ground routes avoid footprints, cross the actual bridge and reach west-bank camps; flyers use air routes');
for(const type of ['tree','rock','gem-box']){const state=M.initialState(1000);state.obstacles=[{id:type,type,x:10,z:10}];const start=M.clearObstacle(state,type,1000,()=>.1);assert.ok(start.ok);const item=workItems(state,4000).find(w=>w.kind==='obstacle');assert.ok(item&&item.progress>0&&item.progress<1);assert.ok(item.remaining>0);const before=state.gems;assert.ok(M.applyAction(state,{type:'skip',kind:'obstacle',id:type},4000).ok);assert.ok(!state.obstacles.some(o=>o.id===type));assert.ok(state.gems>=before-item.gems);}
console.log('PASS Tree, rock and Gem Box removal exposes countdown/progress and authoritative Gem completion');
const original=Math.random;try{for(const rock of [false,true]){const state=M.initialState(1000);state.buildings=[];state.obstacles=[];state.nextObstacleAt=1000;Math.random=()=>rock?.9:.1;M.advanceProgression(state,1001);assert.ok(state.obstacles.some(o=>o.type===(rock?'rock':'tree')));assert.ok(state.nextObstacleAt>1001);}}finally{Math.random=original;}
console.log('PASS Periodic regrowth produces both trees and rocks and schedules the next interval');

const {World}=await import('../dist/world.js');const THREE=await import('../dist/assets/three.module.js');const world={scene:new THREE.Group(),callbacks:{notice(){}}};s.army={};s.research={};World.prototype.setCampArmy.call(world,s,false);s.army.guardian=1;World.prototype.setCampArmy.call(world,s,false);const first=world.campArmy.children[0];assert.ok(Math.hypot(first.position.x-4,first.position.z-6)<2);assert.ok(first.userData.path.some(p=>p.x<-15&&p.x>-23));s.army.ranger=1;World.prototype.setCampArmy.call(world,s,false);assert.equal(world.campArmy.children[0],first);assert.equal(world.campArmy.children.length,2);for(const m of world.campArmy.children){assert.ok(m.userData.path.length);advanceRoute(m.position,m.userData.path,300);assert.ok(m.position.x<-23);}
console.log('PASS Newly trained units start at Barracks, retain in-progress journeys, and arrive at the assigned Camp');
